<?php

declare(strict_types=1);

namespace CloudMe\NotifyLaravel\Notifications;

/**
 * Fluent builder for a Notify message sent through a Laravel Notification's
 * toNotify() method - mirrors exactly what cloudme/notify-php's
 * ChannelSender::send() accepts, nothing more.
 *
 * ```php
 * public function toNotify($notifiable): NotifyMessage
 * {
 *     return NotifyMessage::make()
 *         ->channel('sms')
 *         ->message('Buyurtmangiz tayyor');
 * }
 * ```
 */
final class NotifyMessage
{
    private ?string $channel = null;

    private ?string $to = null;

    private ?string $message = null;

    private ?string $subject = null;

    private ?int $templateId = null;

    /** @var array<string, mixed> */
    private array $variables = [];

    private ?string $smsType = null;

    private ?string $idempotencyKey = null;

    public static function make(): self
    {
        return new self;
    }

    /**
     * One of: sms, telegram, whatsapp, voice, email, push.
     */
    public function channel(string $channel): self
    {
        $this->channel = $channel;

        return $this;
    }

    /**
     * The recipient. Optional - if omitted, NotifyChannel asks the
     * notifiable's routeNotificationForNotify() instead.
     */
    public function to(string $to): self
    {
        $this->to = $to;

        return $this;
    }

    public function message(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Email subject line, or push notification title. Ignored by other
     * channels.
     */
    public function subject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Send a pre-approved template instead of a free-text message.
     *
     * @param  array<string, mixed>  $variables  values to substitute into the template's {{placeholders}}
     */
    public function template(int $templateId, array $variables = []): self
    {
        $this->templateId = $templateId;
        $this->variables = $variables;

        return $this;
    }

    /**
     * @param  array<string, mixed>  $variables
     */
    public function variables(array $variables): self
    {
        $this->variables = $variables;

        return $this;
    }

    /**
     * "service" or "advertisement" - only meaningful for the sms channel.
     */
    public function smsType(string $smsType): self
    {
        $this->smsType = $smsType;

        return $this;
    }

    /**
     * Retrying a send with the same key returns the original result instead
     * of sending twice. Auto-generated by the SDK if you never set one.
     */
    public function idempotencyKey(string $idempotencyKey): self
    {
        $this->idempotencyKey = $idempotencyKey;

        return $this;
    }

    public function getChannel(): ?string
    {
        return $this->channel;
    }

    public function getTo(): ?string
    {
        return $this->to;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function getTemplateId(): ?int
    {
        return $this->templateId;
    }

    /**
     * @return array<string, mixed>
     */
    public function getVariables(): array
    {
        return $this->variables;
    }

    public function getSmsType(): ?string
    {
        return $this->smsType;
    }

    public function getIdempotencyKey(): ?string
    {
        return $this->idempotencyKey;
    }
}
